"""criando tabela de chamados

Revision ID: 0779c980fe92
Revises: da03a228f529
Create Date: 2026-09-18 20:02:33.986587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0779c980fe92'
down_revision: Union[str, Sequence[str], None] = 'da03a228f529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tickets',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('status_id', sa.Integer(), nullable=False),
        sa.Column('priority_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('requester_id', sa.Integer(), nullable=False),
        sa.Column('assignee_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_foreign_key(
        'fk_tickets_status_id_ticket_statuses',
        'tickets',
        'ticket_statuses',
        ['status_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_tickets_priority_id_ticket_priorities',
        'tickets',
        'ticket_priorities',
        ['priority_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_tickets_category_id_ticket_categories',
        'tickets',
        'ticket_categories',
        ['category_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_tickets_requester_id_users',
        'tickets',
        'users',
        ['requester_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_tickets_assignee_id_users',
        'tickets',
        'users',
        ['assignee_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_tickets_assignee_id_users',
        'tickets',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_tickets_requester_id_users',
        'tickets',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_tickets_category_id_ticket_categories',
        'tickets',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_tickets_priority_id_ticket_priorities',
        'tickets',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_tickets_status_id_ticket_statuses',
        'tickets',
        type_='foreignkey',
    )

    op.drop_table('tickets')
    # ### end Alembic commands ###