"""criando tabela de histórico de chamados

Revision ID: 1ef06e964747
Revises: 65730a11a4a3
Create Date: 2026-09-18 20:23:33.318975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef06e964747'
down_revision: Union[str, Sequence[str], None] = '65730a11a4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ticket_histories',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('ticket_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_foreign_key(
        'fk_ticket_histories_ticket_id_tickets',
        'ticket_histories',
        'tickets',
        ['ticket_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_ticket_histories_user_id_users',
        'ticket_histories',
        'users',
        ['user_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_ticket_histories_user_id_users',
        'ticket_histories',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_ticket_histories_ticket_id_tickets',
        'ticket_histories',
        type_='foreignkey',
    )

    op.drop_table('ticket_histories')
    # ### end Alembic commands ###