"""criando tabela de comentarios de chamados

Revision ID: 65730a11a4a3
Revises: 0779c980fe92
Create Date: 2026-09-18 20:16:56.113066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65730a11a4a3'
down_revision: Union[str, Sequence[str], None] = '0779c980fe92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ticket_comments',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('ticket_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_foreign_key(
        'fk_ticket_comments_ticket_id_tickets',
        'ticket_comments',
        'tickets',
        ['ticket_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_ticket_comments_user_id_users',
        'ticket_comments',
        'users',
        ['user_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_ticket_comments_user_id_users',
        'ticket_comments',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_ticket_comments_ticket_id_tickets',
        'ticket_comments',
        type_='foreignkey',
    )

    op.drop_table('ticket_comments')
    # ### end Alembic commands ###