"""criando sistemas e controles de acesso

Revision ID: 7a0306ecce02
Revises: af79ae4bf829
Create Date: 2026-09-26 21:12:38.997406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0306ecce02'
down_revision: Union[str, Sequence[str], None] = 'af79ae4bf829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        'systems',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )

    op.create_table(
        'system_modules',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('system_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'system_id',
            'name',
            name='uq_system_modules_system_name',
        ),
    )

    op.create_foreign_key(
        'fk_sys_modules_system',
        'system_modules',
        'systems',
        ['system_id'],
        ['id'],
    )

    op.create_table(
        'system_features',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('module_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'module_id',
            'name',
            name='uq_system_features_module_name',
        ),
    )

    op.create_foreign_key(
        'fk_sys_features_module',
        'system_features',
        'system_modules',
        ['module_id'],
        ['id'],
    )

    op.create_table(
        'repository_access',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('repository_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('profile_id', sa.Integer(), nullable=True),
        sa.Column('sector_id', sa.Integer(), nullable=True),
        sa.Column('permission', sa.String(length=20), nullable=False),
        sa.Column('effect', sa.String(length=10), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "effect IN ('ALLOW', 'DENY')",
            name='ck_repository_access_effect',
        ),
        sa.CheckConstraint(
            "permission IN ('READ', 'WRITE', 'MODIFY', 'DELETE', 'ADMIN')",
            name='ck_repository_access_permission',
        ),
        sa.CheckConstraint(
            'num_nonnulls(user_id, profile_id, sector_id) = 1',
            name='ck_repository_access_subject',
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_index(
        'uq_repo_access_profile_perm',
        'repository_access',
        ['repository_id', 'profile_id', 'permission'],
        unique=True,
        postgresql_where=sa.text('profile_id IS NOT NULL'),
    )

    op.create_index(
        'uq_repo_access_sector_perm',
        'repository_access',
        ['repository_id', 'sector_id', 'permission'],
        unique=True,
        postgresql_where=sa.text('sector_id IS NOT NULL'),
    )

    op.create_index(
        'uq_repo_access_user_perm',
        'repository_access',
        ['repository_id', 'user_id', 'permission'],
        unique=True,
        postgresql_where=sa.text('user_id IS NOT NULL'),
    )

    op.create_foreign_key(
        'fk_repo_access_repository',
        'repository_access',
        'file_repositories',
        ['repository_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_repo_access_user',
        'repository_access',
        'users',
        ['user_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_repo_access_profile',
        'repository_access',
        'profiles',
        ['profile_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_repo_access_sector',
        'repository_access',
        'sectors',
        ['sector_id'],
        ['id'],
    )

    op.create_table(
        'folder_access',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('folder_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('profile_id', sa.Integer(), nullable=True),
        sa.Column('sector_id', sa.Integer(), nullable=True),
        sa.Column('permission', sa.String(length=20), nullable=False),
        sa.Column('effect', sa.String(length=10), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "effect IN ('ALLOW', 'DENY')",
            name='ck_folder_access_effect',
        ),
        sa.CheckConstraint(
            "permission IN ('READ', 'WRITE', 'MODIFY', 'DELETE', 'ADMIN')",
            name='ck_folder_access_permission',
        ),
        sa.CheckConstraint(
            'num_nonnulls(user_id, profile_id, sector_id) = 1',
            name='ck_folder_access_subject',
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_index(
        'uq_folder_access_profile_perm',
        'folder_access',
        ['folder_id', 'profile_id', 'permission'],
        unique=True,
        postgresql_where=sa.text('profile_id IS NOT NULL'),
    )

    op.create_index(
        'uq_folder_access_sector_perm',
        'folder_access',
        ['folder_id', 'sector_id', 'permission'],
        unique=True,
        postgresql_where=sa.text('sector_id IS NOT NULL'),
    )

    op.create_index(
        'uq_folder_access_user_perm',
        'folder_access',
        ['folder_id', 'user_id', 'permission'],
        unique=True,
        postgresql_where=sa.text('user_id IS NOT NULL'),
    )

    op.create_foreign_key(
        'fk_folder_access_folder',
        'folder_access',
        'folders',
        ['folder_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_folder_access_user',
        'folder_access',
        'users',
        ['user_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_folder_access_profile',
        'folder_access',
        'profiles',
        ['profile_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_folder_access_sector',
        'folder_access',
        'sectors',
        ['sector_id'],
        ['id'],
    )

    op.create_table(
        'file_access',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('file_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('profile_id', sa.Integer(), nullable=True),
        sa.Column('sector_id', sa.Integer(), nullable=True),
        sa.Column('permission', sa.String(length=20), nullable=False),
        sa.Column('effect', sa.String(length=10), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "effect IN ('ALLOW', 'DENY')",
            name='ck_file_access_effect',
        ),
        sa.CheckConstraint(
            "permission IN ('READ', 'WRITE', 'MODIFY', 'DELETE', 'ADMIN')",
            name='ck_file_access_permission',
        ),
        sa.CheckConstraint(
            'num_nonnulls(user_id, profile_id, sector_id) = 1',
            name='ck_file_access_subject',
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_index(
        'uq_file_access_profile_perm',
        'file_access',
        ['file_id', 'profile_id', 'permission'],
        unique=True,
        postgresql_where=sa.text('profile_id IS NOT NULL'),
    )

    op.create_index(
        'uq_file_access_sector_perm',
        'file_access',
        ['file_id', 'sector_id', 'permission'],
        unique=True,
        postgresql_where=sa.text('sector_id IS NOT NULL'),
    )

    op.create_index(
        'uq_file_access_user_perm',
        'file_access',
        ['file_id', 'user_id', 'permission'],
        unique=True,
        postgresql_where=sa.text('user_id IS NOT NULL'),
    )

    op.create_foreign_key(
        'fk_file_access_file',
        'file_access',
        'files',
        ['file_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_file_access_user',
        'file_access',
        'users',
        ['user_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_file_access_profile',
        'file_access',
        'profiles',
        ['profile_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_file_access_sector',
        'file_access',
        'sectors',
        ['sector_id'],
        ['id'],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        'fk_file_access_sector',
        'file_access',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_file_access_profile',
        'file_access',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_file_access_user',
        'file_access',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_file_access_file',
        'file_access',
        type_='foreignkey',
    )

    op.drop_index(
        'uq_file_access_user_perm',
        table_name='file_access',
    )

    op.drop_index(
        'uq_file_access_sector_perm',
        table_name='file_access',
    )

    op.drop_index(
        'uq_file_access_profile_perm',
        table_name='file_access',
    )

    op.drop_table('file_access')

    op.drop_constraint(
        'fk_folder_access_sector',
        'folder_access',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_folder_access_profile',
        'folder_access',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_folder_access_user',
        'folder_access',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_folder_access_folder',
        'folder_access',
        type_='foreignkey',
    )

    op.drop_index(
        'uq_folder_access_user_perm',
        table_name='folder_access',
    )

    op.drop_index(
        'uq_folder_access_sector_perm',
        table_name='folder_access',
    )

    op.drop_index(
        'uq_folder_access_profile_perm',
        table_name='folder_access',
    )

    op.drop_table('folder_access')

    op.drop_constraint(
        'fk_repo_access_sector',
        'repository_access',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_repo_access_profile',
        'repository_access',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_repo_access_user',
        'repository_access',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_repo_access_repository',
        'repository_access',
        type_='foreignkey',
    )

    op.drop_index(
        'uq_repo_access_user_perm',
        table_name='repository_access',
    )

    op.drop_index(
        'uq_repo_access_sector_perm',
        table_name='repository_access',
    )

    op.drop_index(
        'uq_repo_access_profile_perm',
        table_name='repository_access',
    )

    op.drop_table('repository_access')

    op.drop_constraint(
        'fk_sys_features_module',
        'system_features',
        type_='foreignkey',
    )

    op.drop_table('system_features')

    op.drop_constraint(
        'fk_sys_modules_system',
        'system_modules',
        type_='foreignkey',
    )

    op.drop_table('system_modules')

    op.drop_table('systems')

    # ### end Alembic commands ###