"""criando estrutura de documentos e repositorio

Revision ID: 7e9cfda78c1d
Revises: e7dd2fa144aa
Create Date: 2026-09-23 19:42:31.283750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9cfda78c1d'
down_revision: Union[str, Sequence[str], None] = 'e7dd2fa144aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        'file_repositories',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )

    op.create_table(
        'folders',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('repository_id', sa.Integer(), nullable=False),
        sa.Column('parent_folder_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_index(
        'uq_folders_root_name',
        'folders',
        ['repository_id', 'name'],
        unique=True,
        postgresql_where=sa.text('parent_folder_id IS NULL'),
    )

    op.create_index(
        'uq_folders_child_name',
        'folders',
        ['repository_id', 'parent_folder_id', 'name'],
        unique=True,
        postgresql_where=sa.text('parent_folder_id IS NOT NULL'),
    )

    op.create_foreign_key(
        'fk_folders_repository_id_file_repositories',
        'folders',
        'file_repositories',
        ['repository_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_folders_parent_folder_id_folders',
        'folders',
        'folders',
        ['parent_folder_id'],
        ['id'],
    )

    op.create_table(
        'documents',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('document_type', sa.String(length=100), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_foreign_key(
        'fk_documents_created_by_id_users',
        'documents',
        'users',
        ['created_by_id'],
        ['id'],
    )

    op.create_table(
        'files',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('folder_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('storage_path', sa.String(length=500), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('mime_type', sa.String(length=100), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_index(
        'uq_files_folder_name_active',
        'files',
        ['folder_id', 'name'],
        unique=True,
        postgresql_where=sa.text('is_active = true'),
    )

    op.create_foreign_key(
        'fk_files_folder_id_folders',
        'files',
        'folders',
        ['folder_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_files_created_by_id_users',
        'files',
        'users',
        ['created_by_id'],
        ['id'],
    )

    op.create_table(
        'document_versions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('change_summary', sa.Text(), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'document_id',
            'version_number',
            name='uq_document_versions_document_version',
        ),
    )

    op.create_foreign_key(
        'fk_document_versions_document_id_documents',
        'document_versions',
        'documents',
        ['document_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_document_versions_created_by_id_users',
        'document_versions',
        'users',
        ['created_by_id'],
        ['id'],
    )

    op.create_table(
        'file_versions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('file_id', sa.Integer(), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('storage_path', sa.String(length=500), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('mime_type', sa.String(length=100), nullable=False),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'file_id',
            'version_number',
            name='uq_file_versions_file_version',
        ),
    )

    op.create_foreign_key(
        'fk_file_versions_file_id_files',
        'file_versions',
        'files',
        ['file_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_file_versions_created_by_id_users',
        'file_versions',
        'users',
        ['created_by_id'],
        ['id'],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        'fk_file_versions_created_by_id_users',
        'file_versions',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_file_versions_file_id_files',
        'file_versions',
        type_='foreignkey',
    )

    op.drop_table('file_versions')

    op.drop_constraint(
        'fk_document_versions_created_by_id_users',
        'document_versions',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_document_versions_document_id_documents',
        'document_versions',
        type_='foreignkey',
    )

    op.drop_table('document_versions')

    op.drop_constraint(
        'fk_files_created_by_id_users',
        'files',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_files_folder_id_folders',
        'files',
        type_='foreignkey',
    )

    op.drop_index(
        'uq_files_folder_name_active',
        table_name='files',
    )

    op.drop_table('files')

    op.drop_constraint(
        'fk_documents_created_by_id_users',
        'documents',
        type_='foreignkey',
    )

    op.drop_table('documents')

    op.drop_constraint(
        'fk_folders_parent_folder_id_folders',
        'folders',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_folders_repository_id_file_repositories',
        'folders',
        type_='foreignkey',
    )

    op.drop_index(
        'uq_folders_child_name',
        table_name='folders',
    )

    op.drop_index(
        'uq_folders_root_name',
        table_name='folders',
    )

    op.drop_table('folders')

    op.drop_table('file_repositories')

    # ### end Alembic commands ###