"""criando estrutura de solicitacoes e acessos

Revision ID: af79ae4bf829
Revises: 7e9cfda78c1d
Create Date: 2026-09-24 17:20:51.548775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'af79ae4bf829'
down_revision: Union[str, Sequence[str], None] = '7e9cfda78c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        'access_resources',
        sa.Column(
            'id',
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            'resource_type',
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            'name',
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column(
            'description',
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            'location',
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'resource_type',
            'name',
            name='uq_access_resources_type_name',
        ),
    )

    op.create_table(
        'request_statuses',
        sa.Column(
            'id',
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            'name',
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            'description',
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )

    op.create_table(
        'requests',
        sa.Column(
            'id',
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            'protocol',
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            'title',
            sa.String(length=200),
            nullable=False,
        ),
        sa.Column(
            'description',
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            'requester_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'status_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('protocol'),
    )

    op.create_foreign_key(
        'fk_requests_requester_id_users',
        'requests',
        'users',
        ['requester_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_requests_status_id_request_statuses',
        'requests',
        'request_statuses',
        ['status_id'],
        ['id'],
    )

    op.create_table(
        'access_requests',
        sa.Column(
            'id',
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            'request_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'operation_type',
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            'justification',
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            'period_type',
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            'start_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            'end_at',
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "operation_type IN ('NEW', 'CHANGE', 'REVOKE')",
            name='ck_access_requests_operation_type',
        ),
        sa.CheckConstraint(
            "period_type IN ('PERMANENT', 'TEMPORARY')",
            name='ck_access_requests_period_type',
        ),
        sa.CheckConstraint(
            'end_at IS NULL OR start_at IS NULL OR end_at > start_at',
            name='ck_access_requests_valid_period',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'request_id',
            name='uq_access_requests_request_id',
        ),
    )

    op.create_foreign_key(
        'fk_access_requests_request_id_requests',
        'access_requests',
        'requests',
        ['request_id'],
        ['id'],
    )

    op.create_table(
        'access_request_resources',
        sa.Column(
            'id',
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            'access_request_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'access_resource_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'requested_scope',
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            'requested_permissions',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            'justification',
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_foreign_key(
        'fk_access_request_resources_access_request_id_access_requests',
        'access_request_resources',
        'access_requests',
        ['access_request_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_access_request_resources_access_resource_id_access_resources',
        'access_request_resources',
        'access_resources',
        ['access_resource_id'],
        ['id'],
    )

    op.create_table(
        'access_grants',
        sa.Column(
            'id',
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            'access_request_resource_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'granted_scope',
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            'granted_permissions',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            'effective_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            'expires_at',
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            'granted_by_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_foreign_key(
        'fk_access_grants_request_resource_id',
        'access_grants',
        'access_request_resources',
        ['access_request_resource_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_access_grants_granted_by_id_users',
        'access_grants',
        'users',
        ['granted_by_id'],
        ['id'],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        'fk_access_grants_granted_by_id_users',
        'access_grants',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_access_grants_request_resource_id',
        'access_grants',
        type_='foreignkey',
    )

    op.drop_table('access_grants')

    op.drop_constraint(
        'fk_access_request_resources_access_resource_id_access_resources',
        'access_request_resources',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_access_request_resources_access_request_id_access_requests',
        'access_request_resources',
        type_='foreignkey',
    )

    op.drop_table('access_request_resources')

    op.drop_constraint(
        'fk_access_requests_request_id_requests',
        'access_requests',
        type_='foreignkey',
    )

    op.drop_table('access_requests')

    op.drop_constraint(
        'fk_requests_status_id_request_statuses',
        'requests',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_requests_requester_id_users',
        'requests',
        type_='foreignkey',
    )

    op.drop_table('requests')

    op.drop_table('request_statuses')
    op.drop_table('access_resources')

    # ### end Alembic commands ###