"""adicionando setor ao usuario

Revision ID: afd025761256
Revises: d1dbf819b76e
Create Date: 2026-09-15 20:12:43.294482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd025761256'
down_revision: Union[str, Sequence[str], None] = 'd1dbf819b76e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sector_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_users_sector_id_sectors', 'users', 'sectors', ['sector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_users_sector_id_sectors', 'users', type_='foreignkey')
    op.drop_column('users', 'sector_id')
    # ### end Alembic commands ###
