"""criando tabela de anexos de chamados

Revision ID: b44b279f4dbc
Revises: 1ef06e964747
Create Date: 2026-09-18 20:31:37.969743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44b279f4dbc'
down_revision: Union[str, Sequence[str], None] = '1ef06e964747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_foreign_key(
    'fk_ticket_attachments_ticket_id_tickets',
    'ticket_attachments',
    'tickets',
    ['ticket_id'],
    ['id'],
)

op.create_foreign_key(
    'fk_ticket_attachments_user_id_users',
    'ticket_attachments',
    'users',
    ['user_id'],
    ['id'],
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
    'fk_ticket_attachments_user_id_users',
    'ticket_attachments',
    type_='foreignkey',
)

op.drop_constraint(
    'fk_ticket_attachments_ticket_id_tickets',
    'ticket_attachments',
    type_='foreignkey',
)

op.drop_table('ticket_attachments')
    # ### end Alembic commands ###
