"""Criando estrutura inicial de processos

Revision ID: e7dd2fa144aa
Revises: a50e8bfd1866
Create Date: 2026-09-22 18:46:15.739048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7dd2fa144aa'
down_revision: Union[str, Sequence[str], None] = 'a50e8bfd1866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'process_statuses',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )

    op.create_table(
        'process_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )

    op.create_table(
        'processes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('protocol', sa.String(length=30), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('process_type_id', sa.Integer(), nullable=False),
        sa.Column('status_id', sa.Integer(), nullable=False),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('responsible_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('protocol'),
    )

    op.create_foreign_key(
        'fk_processes_process_type_id_process_types',
        'processes',
        'process_types',
        ['process_type_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_processes_status_id_process_statuses',
        'processes',
        'process_statuses',
        ['status_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_processes_created_by_id_users',
        'processes',
        'users',
        ['created_by_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_processes_responsible_id_users',
        'processes',
        'users',
        ['responsible_id'],
        ['id'],
    )

    op.create_table(
        'process_progress',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('process_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_foreign_key(
        'fk_process_progress_process_id_processes',
        'process_progress',
        'processes',
        ['process_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_process_progress_user_id_users',
        'process_progress',
        'users',
        ['user_id'],
        ['id'],
    )

    op.create_table(
        'process_stages',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('process_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('sequence', sa.Integer(), nullable=False),
        sa.Column('responsible_id', sa.Integer(), nullable=True),
        sa.Column('is_completed', sa.Boolean(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_foreign_key(
        'fk_process_stages_process_id_processes',
        'process_stages',
        'processes',
        ['process_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_process_stages_responsible_id_users',
        'process_stages',
        'users',
        ['responsible_id'],
        ['id'],
    )

    op.create_table(
        'tasks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('process_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('assigned_to_id', sa.Integer(), nullable=True),
        sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_completed', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_foreign_key(
        'fk_tasks_process_id_processes',
        'tasks',
        'processes',
        ['process_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_tasks_assigned_to_id_users',
        'tasks',
        'users',
        ['assigned_to_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:  
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_tasks_assigned_to_id_users',
        'tasks',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_tasks_process_id_processes',
        'tasks',
        type_='foreignkey',
    )

    op.drop_table('tasks')

    op.drop_constraint(
        'fk_process_stages_responsible_id_users',
        'process_stages',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_process_stages_process_id_processes',
        'process_stages',
        type_='foreignkey',
    )

    op.drop_table('process_stages')

    op.drop_constraint(
        'fk_process_progress_user_id_users',
        'process_progress',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_process_progress_process_id_processes',
        'process_progress',
        type_='foreignkey',
    )

    op.drop_table('process_progress')

    op.drop_constraint(
        'fk_processes_responsible_id_users',
        'processes',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_processes_created_by_id_users',
        'processes',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_processes_status_id_process_statuses',
        'processes',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_processes_process_type_id_process_types',
        'processes',
        type_='foreignkey',
    )

    op.drop_table('processes')

    op.drop_table('process_types')
    op.drop_table('process_statuses')
    # ### end Alembic commands ###