"""criando aprovacoes notificacoes e complementos de processos

Revision ID: f01ed27af4b0
Revises: 7a0306ecce02
Create Date: 2026-09-28 18:50:27.464010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01ed27af4b0'
down_revision: Union[str, Sequence[str], None] = '7a0306ecce02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        'notifications',
        sa.Column(
            'id',
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            'user_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'notification_type',
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            'title',
            sa.String(length=200),
            nullable=False,
        ),
        sa.Column(
            'message',
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            'resource_type',
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            'resource_id',
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            'is_read',
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            'read_at',
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_foreign_key(
        'fk_notifications_user',
        'notifications',
        'users',
        ['user_id'],
        ['id'],
    )

    op.create_table(
        'approvals',
        sa.Column(
            'id',
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            'process_id',
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            'request_id',
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            'approver_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'approval_order',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            'decision_comment',
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            'requested_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            'decided_at',
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'PENDING' AND decided_at IS NULL) "
            "OR (status <> 'PENDING' AND decided_at IS NOT NULL)",
            name='ck_approvals_decision_date',
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')",
            name='ck_approvals_status',
        ),
        sa.CheckConstraint(
            'num_nonnulls(process_id, request_id) = 1',
            name='ck_approvals_target',
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_foreign_key(
        'fk_approvals_approver',
        'approvals',
        'users',
        ['approver_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_approvals_process',
        'approvals',
        'processes',
        ['process_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_approvals_request',
        'approvals',
        'requests',
        ['request_id'],
        ['id'],
    )

    op.create_table(
        'process_documents',
        sa.Column(
            'id',
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            'process_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'document_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'linked_by_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'process_id',
            'document_id',
            name='uq_process_documents_process_document',
        ),
    )

    op.create_foreign_key(
        'fk_process_documents_process',
        'process_documents',
        'processes',
        ['process_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_process_documents_document',
        'process_documents',
        'documents',
        ['document_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_process_documents_linked_by',
        'process_documents',
        'users',
        ['linked_by_id'],
        ['id'],
    )

    op.create_table(
        'process_stage_history',
        sa.Column(
            'id',
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            'process_stage_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'user_id',
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            'action',
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            'description',
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_foreign_key(
        'fk_process_stage_history_stage',
        'process_stage_history',
        'process_stages',
        ['process_stage_id'],
        ['id'],
    )

    op.create_foreign_key(
        'fk_process_stage_history_user',
        'process_stage_history',
        'users',
        ['user_id'],
        ['id'],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        'fk_process_stage_history_user',
        'process_stage_history',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_process_stage_history_stage',
        'process_stage_history',
        type_='foreignkey',
    )

    op.drop_table('process_stage_history')

    op.drop_constraint(
        'fk_process_documents_linked_by',
        'process_documents',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_process_documents_document',
        'process_documents',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_process_documents_process',
        'process_documents',
        type_='foreignkey',
    )

    op.drop_table('process_documents')

    op.drop_constraint(
        'fk_approvals_request',
        'approvals',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_approvals_process',
        'approvals',
        type_='foreignkey',
    )

    op.drop_constraint(
        'fk_approvals_approver',
        'approvals',
        type_='foreignkey',
    )

    op.drop_table('approvals')

    op.drop_constraint(
        'fk_notifications_user',
        'notifications',
        type_='foreignkey',
    )

    op.drop_table('notifications')

    # ### end Alembic commands ###